---
title: "Advanced R"
author: "Project Assignment"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  bookdown::word_document2: default
  bookdown::pdf_document2: default
  pdf_document: default
  word_document: default
  fig_caption: yes
tables: yes
fontsize: 14pt
mainfont: Arial
fig_caption: yes
number_sections: yes
toc: no
header-includes: \usepackage{amsmath}
editor_options: 
  chunk_output_type: console
---



```{r setup, child="_setup.Rmd"}
# knitr::opts_chunk$set(echo = TRUE)

```

# Chapter Exercises

## Data Structures

### Exercise 1

1. What are the six types of atomic vector? How does a list differ from an atomic vector?
Six types of atomic vectors: integer, logical, double, character, complex and raw. Elements of a list don't have to be of the same type.

2. What makes `is.vector()` and `is.numeric()` fundamentally different to `is.list()` and `is.character()`?
The first two sets don't check for a particular type

4. Why do you need to use `unlist()` to convert a list to an atomic vector? Why doesn't `as.vector()` work?
`unlist()` flattens the nested structure; `as.vector()` only applicable to unnested elements 

5. Why is 1 == "1" true? Why is -1 < FALSE true? Why is "one" < 2 false?
The first instance, 1 is coerced to "1" resulting to TRUE. In the latter, "2" comes before "one" in ASCII.

6. Why is the default missing value, NA, a logical vector? What's special about logical vectors? (Hint: think about c(FALSE, NA_character_).)

Logical vectors get coerced to other vectors when concatenated together. e.g. c(FALSE, NA_character_) results into c("FALSE", NA). The NA does not lose its meaning, whichever vector you combine it with.
