---
title:  "Air pollution, PM2.5 mean annual exposure
        (micrograms per cubic meter), 2016.Source: World Bank https://data.worldbank.org"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
ipk = function(pkg){
  new.pkg = list.of.pkgs[!(list.of.pkgs %in% .packages(all.available = T))]
  if(length(new.pkg)) install.packages(new.pkg, dependencies = T)
  sapply(pkg, require, character.only = T)
}

list.of.pkgs = c("rnaturalearth", "wbstats", "leaflet", "DT", "ggplot2", "cowplot", "tidyverse")

ipk(list.of.pkgs)

map = ne_countries()

names(map)[names(map) == "iso_a3"] = "ISO3"
names(map)[names(map) == "name"] = "NAME"

d = wb(indicator = "EN.ATM.PM25.MC.M3",
        startdate = 2016, enddate = 2016)
map$PM2.5 = d[match(map$ISO3, d$iso3), "value"]
```

Column {.sidebar data-width=200}
------------------------------------

```{r}

minvalue = floor(min(map$PM2.5, na.rm = T))
maxvalue = ceiling(max(map$PM2.5, na.rm = T))

sliderInput("rangevalues",
            label = "PM2.5 values:",
            min = minvalue, max = maxvalue,
            value = c(minvalue, maxvalue)
)
```

Column {data-width=500}
-----------------------------------

### map

```{r}
pal <- colorBin(
  palette = "viridis", domain = map$PM2.5,
  bins = seq(0, max(map$PM2.5, na.rm = TRUE) + 10, by = 10)
)


map$labels <- paste0(
  "<strong> Country: </strong> ",
  map$NAME, "<br/> ",
  "<strong> PM2.5: </strong> ",
  map$PM2.5, "<br/> "
) %>%
  lapply(htmltools::HTML)


mapFiltered <- reactive({
  rowsinrangeslider <- which(map$PM2.5 >= input$rangevalues[1] &
    map$PM2.5 <= input$rangevalues[2])
  map[rowsinrangeslider, ]
})

renderLeaflet({
  if (nrow(mapFiltered()) == 0) {
    return(NULL)
  }

  leaflet(mapFiltered()) %>%
    addTiles() %>%
    setView(lng = 0, lat = 30, zoom = 2) %>%
    addPolygons(
      fillColor = ~ pal(PM2.5),
      color = "white",
      fillOpacity = 0.7,
      label = ~labels,
      highlight = highlightOptions(
        color = "black",
        bringToFront = TRUE
      )
    ) %>%
    leaflet::addLegend(
      pal = pal, values = ~PM2.5,
      opacity = 0.7, title = "PM2.5"
    )
})

```

Column {data-width=300}
--------------------------------

### Table

```{r}
renderDT({
  # DT::datatable(mapFiltered()@data[, c("ISO3", "NAME", "PM2.5")],
  #   rownames = FALSE, options = list(pageLength = 10)
  # )
  mapFiltered()@data %>%
    select(., c("ISO3", "NAME", "PM2.5")) %>%
    DT::datatable(., rownames = F, options = list(pageLength = 10))
})
```

### Hist

```{r}
renderPlot({
  ggplot(mapFiltered()@data, aes(x = PM2.5)) + geom_histogram() + 
    theme_minimal_hgrid(12, rel_small = 1)
})
```






