---
title:  "Air pollution, PM2.5 mean annual exposure
        (micrograms per cubic meter), 2016.Source: World Bank         https://data.worldbank.org"
output: flexdashboard::flex_dashboard
---


```{r}
library(rnaturalearth)
library(wbstats)
library(leaflet)
library(DT)
library(ggplot2)
library(dplyr)
library(cowplot)

map <- ne_countries()
names(map)[names(map) == "iso_a3"] <- "ISO3"
names(map)[names(map) == "name"] <- "NAME"

d <- wb(
  indicator = "EN.ATM.PM25.MC.M3",
  startdate = 2016, enddate = 2016
)

map$PM2.5 <- d[match(map$ISO3, d$iso3), "value"]
```
  
  
Column {data-width=600}
-------------------------------------

### Map


```{r}
pal <- colorBin(
  palette = "viridis", domain = map$PM2.5,
  bins = seq(0, max(map$PM2.5, na.rm = TRUE) + 10, by = 10)
)

map$labels <- paste0(
  "<strong> Country: </strong> ",
  map$NAME, "<br/> ",
  "<strong> PM2.5: </strong> ",
  map$PM2.5, "<br/> "
) %>%
  lapply(htmltools::HTML)

leaflet(map) %>%
  addTiles() %>%
  setView(lng = 0, lat = 30, zoom = 2) %>%
  addPolygons(
    fillColor = ~ pal(PM2.5),
    color = "white",
    fillOpacity = 0.7,
    label = ~labels,
    highlight = highlightOptions(
      color = "black",
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~PM2.5,
    opacity = 0.7, title = "PM2.5"
  )
```
   

Column {data-width=400}
-------------------------------------

### Table


```{r}
map@data %>%
  select(., c("ISO3", "NAME", "PM2.5")) %>%
  arrange(., desc(PM2.5)) %>%
  DT::datatable(., rownames = F, options =list(pageLength = 10) 
    
  )
```   

### Histogram


```{r}
ggplot(data = map@data, aes(x = PM2.5)) + geom_histogram() +
  theme_minimal_hgrid(12, rel_small = 1) # font size 12 pt throughout
```