---
title: "Hands-On programming with R"
date: '`r format(Sys.time(), "%B %d, %Y")`'
author: "BOkola"
output: 
  html_notebook:
    toc: yes
    toc_depth: 3
    highlight: tango
---
# **Chapter1: The very Basics**

## **Writing Own Functions**
```{r}
roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = T, prob = c(rep(1/8, 5), 3/8))
  sum(dice)
}
roll()
replicate(1000, roll())

roll2 <- function(n) {
  dice <- sample(n, size = 2, replace = T)
  sum(dice)
  
}
roll2(n = 1:6)
roll2(1:5)

odds <- function() {
  odd <- 0:2
  result <- sample(odd, size = 1, replace = T)
  result
  
}
replicate(17,odds())

```
# **Project 2: Playing Cards**
## ** Chapter 3: R Objects**
```{r, R Objects}
hand <- c("ace", "king", "queen", "jack", "ten")
hand1 <- c("ace", "king", "queen", "jack", "ten", "spades", "spades",
"spades", "spades", "spades")
matrix(hand1, nrow = 5)
matrix(hand1, ncol = 2)
dim(hand1) <- c(5, 2)
# lists
card <- list("ace", "hearts", 1)
card
deck <- read.csv("C:/Users/bokola/Analysis/DSR/data/deck.csv")
# A function that deals a card
deal <- function(cards){
  cards[1,]
}
deal(deck)
# shuffle the deck
# first extract every row in the df
deck2 <- deck[1:nrow(deck),]
deck3 <- deck[c(2,1, 3:nrow(deck)),]; head(deck3)

# this is better achieved with `sample`
random <- sample(1:52, size = 52)
deck4 <- deck[random,]
# a shuffle function
shuffle <- function(cards) {
  random <- sample(1:52, size = 52)
  cards[random,]
}
deck2 <- shuffle(deck)
deal(deck2)
```
## **Chapter 5: Modifying Values
```{r, modify}
deck2 <- deck
deck2$new <- 1:52 # add new col
deck2$new <- NULL
# modifying value of aces' value from 1 to 14 which are every 13th card
deck2[deck2$face %in% c("ace"),] # find row index
deck2[c(13,26,39,52),3] <- 14

#or 
deck2$value[c(13, 26, 39, 52)] <- 14
```
## **Logical subsetting**
```{r}
deck2$face == "ace"
sum(deck2$face == "ace") # count number of aces
deck2$value[deck2$face == "ace"] # logical subsetting
deck2$value[deck2$face == "ace"] <- 14
# further logical subsetting 
deck4 <- deck
deck4$value <- 0; head(deck4, 13)
deck4$value[deck4$suit == "hearts"] <- 1
# the queen of spades should have 13 points
deck4[deck4$face == "queen",]
queenOfSpades <- deck4$face == "queen" & deck4$suit == "spades"
deck4[queenOfSpades,]
deck4$value[queenOfSpades]<- 13

# blackjack -- number card with a value equal to its face value, face card with a value of 10 and ace with a value of 11 or 1

deck5 <- deck; head(deck5, 13)
facecard<- deck5$face %in% c("king", "queen", "jack")
deck5[facecard,]
deck5$value[facecard] <- 10
deck5$value[deck5$face == "ace"] <- NA
```
## **Chapter 6: Environments**
You can see R's environment with `devtools::parenvs()` function
```{r}
library(devtools)
parenvs()
```
