---
title: "Basil Owiti Okola's CV"
author: Basil Owiti Okola
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'custom.css',  'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
# CV <- create_CV_object(
#   data_location = "https://docs.google.com/spreadsheets/d/1Cq7X-TA6iR0ZVFOD5QkfGxvZOWg3Zz2XnwAMz4YMInE",  
#   pdf_mode = params$pdf_mode
# )
# saveRDS(CV, file.path(dir, "cached_positions.rds"))
CV <- readr::read_rds(file.path(dir,'cached_positions.rds'))
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```


```{r, results="asis"}
if(params$pdf_mode){
  cat("[<i class='fas fa-search'></i> View this CV online](https://github.com/Bokola/Analysis/blob/master/CV%20with%20R/cv_Basil Owiti Okola.pdf)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/Bokola/Analysis/blob/master/CV%20with%20R/cv_Basil Owiti Okola.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Technical Skills {#skills}
--------------------------------------------------------------------------------

- Proficient:

  - R
  - Python
  - Git and Github
  - Bash

- Working knowledge:

  - Arango
  - Graphql
  - SQL 
  - SAS 




Main
================================================================================

Basil Owiti Okola {#title}
--------------------------------------------------------------------------------

Basil is a graduate student pursuing MSc. Statistics and Data Science and has previously held roles as a data manager and analyst. He seeks to leverage statistical, programming and analytic skills in managing, analyzing data and communicating key findings that inform policy makers in their day-today decisions.

```{r}
# Note the special double pipe so we modify the CV object in place
# CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience')
```



Internships {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Internship')
```

::: aside


Made with the R packages: `pagedown` and `datadrivencv`.

The source code is available on [github](https://github.com/Bokola/Analysis/blob/master/CV%20with%20R).

Last updated on `r Sys.Date()`.

:::
