---
title: "nobel prize winners"
author: "bokola"
date: "`r format(Sys.time(), %b,%d,%Y)` "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r packages, message=FALSE, results='hide', warning=FALSE}
ipk = function(pkg){
  new.pkg = list.of.pkgs[!(list.of.pkgs %in% installed.packages()[,"Package"])]
  if(length(new.pkg)) install.packages(new.pkg, dep = T)
  sapply(pkg, require, character.only = T)
}
list.of.pkgs = c("tidyverse")
ipk(list.of.pkgs)
```
Paths

```{r paths, message=FALSE, results='hide', warning=FALSE}
rm(list = ls(all = T))
home.dir = ifelse(Sys.info()["sysname"] == "windows", Sys.getenv("USERPROFILE"), Sys.getenv("HOME"))
m.project.path = path.expand(file.path(home.dir
                                       ,"Analysis"
                                       ,"TidyTuesday"
                                       )) %>% gsub("\\\\", "/", .)
if(!file.exists(m.project.path)) {
  if(dir.create(m.project.path, recursive = T))
    stop("The project directory \"", m.project.path, "\" has been created!\nPlease fill it with relevant files and folders!")
  else
    stop("The project directory \""
, m.project.path
,"\" could not be created!")
}

```
Data
```{r data, results='hide', warning=FALSE, message=FALSE}
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")
nobel_winner_all_pubs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv")
```
```{r, Prize_winners}
nobel_winners = nobel_winners %>% 
  mutate(., decade = 10*(prize_year %/% 10))
p1 = nobel_winners %>% 
  count(category,decade, sort = T) %>%
  ggplot(aes(decade, n, fill = category)) +
  geom_col() # counting winners per decade
# how about group_by()
p2 = nobel_winners %>% 
  group_by(category, decade) %>% 
  summarize(winners = n(), winners_per_year = winners/n_distinct(prize_year)) %>% 
  ggplot(aes(decade, winners_per_year, fill = category)) + 
  geom_col() # bar

p3 = nobel_winners %>% 
  group_by(category, decade) %>% 
  summarize(winners = n(), winners_per_year = winners/n_distinct(prize_year)) %>% 
  ggplot(aes(decade, winners_per_year, color = category)) + 
  geom_line() +
  expand_limits(y=0)#line
```
```{r prize_share}
nobel_winners %>% 
  count(prize_share) # share dist
nobel_winners %>% 
  count(full_name, sort = T)#who's won more prizes
nobel_winners %>% 
  add_count(full_name) %>% 
  arrange(desc(n)) %>%
  select(prize_year, category, full_name) 
 
```