# Function to standardize pumwani variables to be similar to pumwani data

renamePumwani = function(x){
  library(plyr)
  library(dplyr)
 
  x = mutate(x, ifelse(Variable=='survey_id','id', 
                        ifelse(Variable=='randomized','random', 
                        ifelse(Variable=='patients_ipno','ipno',
                        ifelse(Variable=='date_of_discharge_death',"date_discharge",
                        ifelse(Variable=='admission_date','date_adm', 
                        ifelse(Variable=='agedoc','age_recorded', 
                        ifelse(Variable=='age','age_days',
                        ifelse(Variable=='gender','child_sex', 
                        ifelse(Variable=='birth_weight','birth_wt', 
                        ifelse(Variable=='abnormalities___7','abnormalities____1', 
                        ifelse(Variable=='pus_from_the_eyes','eye_pus',
                        ifelse(Variable=='other_admission_diag_not_listed','other_adm_diag_not_listed',
                        ifelse(Variable=='fldte','date_fluid_pres', 
                        ifelse(Variable=='fluid_feed_monitoring_char','fluid_feed_monitoring_chart',
                        ifelse(Variable=='intravenous_fluids_prescri','intravenous_fluids_pres',
                        ifelse(Variable=='total_volume_of_other_flui','total_volume_of_other_fluid', 
                        ifelse(Variable=='frequency_of_administratio','freq_of_administration',
                        ifelse(Variable=='date_the_feeds_are_initiat','date_the_feeds_initiated',
                        ifelse(Variable=='feed_fluid_monitoring_char','feed_fluid_monitoring_chart',
                        ifelse(Variable=='date_of_phototherapy','start_date_phototherapy',
                        ifelse(Variable=='vital_signs_monitored_f48___1','vital_signs_monitored___1',
                        ifelse(Variable=='vital_signs_monitored_f48___2','vital_signs_monitored___2',
                        ifelse(Variable=='vital_signs_monitored_f48___3','vital_signs_monitored___3',
                        ifelse(Variable=='vital_signs_monitored_f48___4','vital_signs_monitored___4',
                        ifelse(Variable=='fld_cht','fluid_monitoring_chart',
                        ifelse(Variable=='dth_sum','disch_death_summ', 
                        ifelse(Variable=="otcme", 'outcome', 
                        ifelse(Variable=='condition_on_discharge','disc_condition', 
                        ifelse(Variable=='refereed_where','referred_where',
                        ifelse(Variable=='follow_up_care','follow_up',
                        ifelse(Variable=='ddgnsis','disc_dx1_primary', 
                        ifelse(Variable=='other_disch_diag_1','disch_diag_4', 
                        ifelse(Variable=='other_disch_diag_2','disch_diag_5', 
                        ifelse(Variable=='other_disch_diag_not_listed','any_other_disch_diag', 
                        ifelse(Variable=='disch_diag_not_listed','other_disch_diag_1',Variable
                        ))))))))))))))))))))))))))))))))))))
    
    # Remove variables not required
  drops <- c('biodata_complete', 'babys_history_complete', 'maternal_history_complete',
             'examination_complete', 'investigations_complete', 'babys_admission_diagnoses_complete',
             'babys_daily_case_notes_complete', 'drug_treatment_complete', 'supportive_care_complete',
             'follow_up_monitoring_complete', 'discharge_information_complete',
             'recid', 'residence_location_sub_loc', 'residence_district',
             're_admission_to_this_hospi', 'bcg_given', 'opv_birth_given', 'ind_cs', 'tindcs','diarrhoea_bloody',
             'diarrhoea_duration', 'ismdrugs', 'maternal_drugs___1', 'maternal_drugs___2', 'maternal_drugs___3',
             'maternal_drugs___4', 'maternal_drugs___5', 'maternal_drugs___6', 'maternal_drugs___7', 'maternal_drugs___8',
             'maternal_drugs___9', 'maternal_drugs___10', 'maternal_drugs___11', 'maternal_drugs___12', 'maternal_drugs___13',
             'maternal_drugs___14', 'maternal_drugs___15', 'maternal_drugs___16', 'maternal_drugs___17', 'idrugs',
             'marital_status', 'mother_s_inpatient_number', 'anc_visuts_documented', 'number_of_documented_anc_v',
             'maternal_abo_blood_group', 'maternal_rhesus_blood_grou', 'last_normal_menstrual_peri',
             'maternal_cdns___1', 'maternal_cdns___2', 'maternal_cdns___3', 'maternal_cdns___4', 'maternal_cdns___5', 
             'maternal_cdns___6', 'maternal_cdns___7', 'maternal_cdns___8', 'maternal_cdns___9', 'othrmatcdn',
             'antibiotics', 'tetanus_toxoid', 'duration_of_labour_hrs', 'induction_augmented', 'btl_done',
             'baby_femoral_pulse', 'murmur', 'skin_cold','stiff_neck',
             'inflmumbilicus','thrush', 'lymph_nodes_1cm', 'visible_severe_wasting', 'floppy_inability_to_suck', 
             'skin_pustules', 'bp_done', 'diast_bp', 'syst_bp', 'femoral_pulse', 'severe_indrawing', 'skin_pinch_sec', 
             'type_of_hb_test', 'units_for_hb_results', 'type_of_glucose_test_reque', 'bilirubin_test_results',
             'chemistry', 'other_investigations', 'other_investigations_done', 
             'adm_diag___1', 'adm_diag___2', 'adm_diag___3', 'adm_diag___4', 'adm_diag___5', 'adm_diag___6', 
             'adm_diag___7', 'adm_diag___8', 'adm_diag___9', 'adm_diag___10', 'adm_diag___11', 'other_diag1', 
             'other_diagnoses', 'specify_other_diag', 'dtfrstrevw', 
             'when_was_the_first_documen', 'sevendyrev', 'number_of_documented_revie','units', 'ceftr_units',
             'amikacin_units', 'teo', 'date_1_teo_prescribed', 'teofreq', 'duration', 'date_1_teo_stopped',
             'any_other_drug', 'other_drugs_not_listed', 'other_treatment_2', 'other_drugs_not_listed_abo',
             'flow_rate', 'route_of_admission', 'date_oxygen_prescribed','cpap_prescriber',
             'cpap_ad_events___1', 'cpap_ad_events___2', 'cpap_ad_events___3', 'cpap_ad_events___4', 'cpap_ad_events___5', 
             'cpap_ad_events___6', 'cpap_ad_events___7', 'cpap_ad_events___8', 'cpap_ad_events___9', 'cpap_ad_events____1',
             'cpap_ad_events_other', 'cpap_outcome', 'volume_of_blood', 'duration_of_transfusion', 'multiple_transfusions',
             'name_of_prescriber_is_legi', 'signature_of_prescriber_is', 'incubator_keep_warm', 'date_incubator_start',
             'date_incubator_stop', 'inc_temp_hum_chart', 'wght', 'wt_frq', 'fld_mnt', 'ddate', 'othr_cndtn_dischg', 
             'any_other_disch_diag', 'other_discharge_diagnosis', 'no_clear_primary_discharge_diagnosis___1', 
             'no_clear_primary_discharge_diagnosis___2', 'no_clear_primary_discharge_diagnosis___3', 
             'no_clear_primary_discharge_diagnosis___4', 'no_clear_primary_discharge_diagnosis___5', 
             'no_clear_primary_discharge_diagnosis___6', 'no_clear_primary_discharge_diagnosis___7', 
             'no_clear_primary_discharge_diagnosis___8', 'no_clear_primary_discharge_diagnosis___9', 
             'other_discharge_diagn2_069', 'disharge_treatment_prescri', 'discharge_treatment_1', 
             'discharge_treatment_2', 'discharge_treatment_3', 'discharge_treatment4', 'discharge_treatment5', 
             'other_disch_treat_1', 'other_disch_treatment', 'othr_drg', 'othr_disch1')
  x = x[ , !(names(x) %in% drops)]
  return(x)
}
